version: '2.3'
services:
  dev:
    container_name: pyG
    image: pytorch_geometric:latest
    runtime: nvidia
    user: "1001:1001"
    #command: jupyter lab --port 8888 --ip=0.0.0.0 --allow-root 
    working_dir: /app/Programs
    volumes:
        - /tmp/.X11-unix:/tmp/.X11-unix
        - /home/yoshida/Programs:/app/Programs
        - /data/:/data
    environment:
        - DISPLAY=unix$DISPLAY
        - TERM=xterm-256color
        - GRANT_SUDO:"yes"
    ports:
        - "8888:8888"
    ulimits:
        memlock: -1
        stack: 67108864
    shm_size: 64g
    #stdin_open: true
    tty: true
